name: Node.js CI/CD

on:
  push:
    branches:
      - dev  # Trigger workflow on push to dev branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build Docker Image
        run: docker-compose -f docker/docker-compose.yml up --build
      - name: Push Docker image to DockerHub
        run: docker push Abolaji2k21/GadgetBackendNodejs
